@ECHO OFF
REM Generate python include file with embedded images using PyEmbeddedImage.
ECHO from wx.lib.embeddedimage import PyEmbeddedImage > images.py
REM Embed all application images
img2py -c -i -a icon_16.png                         images.py
img2py -c -i -a icon_32.png                         images.py
img2py -c -i -a icon_64.png                         images.py
img2py -c -i -a icon_128.png                        images.py
img2py -c -i -a icon_256.png                        images.py
img2py -c -i -a info_16.png                         images.py
img2py -c -i -a info_128.png                        images.py
img2py -c -i -a browse_16.png                       images.py
img2py -c -i -a browse_128.png                      images.py
img2py -c -i -a complete_16.png                       images.py
img2py -c -i -a complete_128.png  -                    images.py
img2py -c -i -a splash.png                         images.py
img2py -c -i -a throbber/frame_0_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_1_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_2_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_3_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_4_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_5_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_6_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_7_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_8_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_9_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_10_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_11_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_12_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_13_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_14_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_15_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_16_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_17_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_18_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_19_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_20_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_21_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_22_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_23_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_24_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_25_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_26_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_27_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_28_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_29_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_30_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_31_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_32_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_33_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_34_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_35_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_36_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_37_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_38_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_39_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_40_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_41_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_42_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_43_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_44_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_45_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_46_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_47_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_48_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_49_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_50_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_51_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_52_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_53_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_54_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_55_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_56_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_57_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_58_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_59_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_60_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_61_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_62_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_63_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_64_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_65_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_66_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_67_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_68_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_69_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_70_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_71_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_72_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_73_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_74_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_75_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_76_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_77_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_78_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_79_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_80_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_81_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_82_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_83_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_84_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_85_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_86_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_87_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_88_delay-0.03s.png    images.py
img2py -c -i -a throbber/frame_89_delay-0.03s.png    images.py
pause